[package]
name = "only_instance"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/only_instance.rs"

[dependencies]
release_channel.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
sysinfo.workspace = true
log.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
paths.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows.workspace = true
